services:
  weather-cloud-run:
    container_name: weather-cloud-run
    build:
      context: .
      dockerfile: Dockerfile
    image: weather-cloud-run:latest
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
