// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	model "github.com/Berchon/weather-cloud-run/internal/business/model"
	mock "github.com/stretchr/testify/mock"
)

// MockGetTemperatureByZipCodeUsecase is an autogenerated mock type for the GetTemperatureByZipCodeUsecase type
type MockGetTemperatureByZipCodeUsecase struct {
	mock.Mock
}

// GetTemperatureByZipCode provides a mock function with given fields: ctx, zipCode
func (_m *MockGetTemperatureByZipCodeUsecase) GetTemperatureByZipCode(ctx context.Context, zipCode model.ZipCode) (*map[string]float64, *model.CustomError) {
	ret := _m.Called(ctx, zipCode)

	if len(ret) == 0 {
		panic("no return value specified for GetTemperatureByZipCode")
	}

	var r0 *map[string]float64
	var r1 *model.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, model.ZipCode) (*map[string]float64, *model.CustomError)); ok {
		return rf(ctx, zipCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ZipCode) *map[string]float64); ok {
		r0 = rf(ctx, zipCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ZipCode) *model.CustomError); ok {
		r1 = rf(ctx, zipCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.CustomError)
		}
	}

	return r0, r1
}

// NewMockGetTemperatureByZipCodeUsecase creates a new instance of MockGetTemperatureByZipCodeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetTemperatureByZipCodeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetTemperatureByZipCodeUsecase {
	mock := &MockGetTemperatureByZipCodeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
