// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	model "github.com/Berchon/weather-cloud-run/internal/business/model"
	mock "github.com/stretchr/testify/mock"
)

// MockGetTemperatureByCepUsecase is an autogenerated mock type for the GetTemperatureByCepUsecase type
type MockGetTemperatureByCepUsecase struct {
	mock.Mock
}

// GetTemperatureByCep provides a mock function with given fields: ctx, cep
func (_m *MockGetTemperatureByCepUsecase) GetTemperatureByCep(ctx context.Context, cep model.CEP) (*string, *model.CustomError) {
	ret := _m.Called(ctx, cep)

	if len(ret) == 0 {
		panic("no return value specified for GetTemperatureByCep")
	}

	var r0 *string
	var r1 *model.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, model.CEP) (*string, *model.CustomError)); ok {
		return rf(ctx, cep)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CEP) *string); ok {
		r0 = rf(ctx, cep)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CEP) *model.CustomError); ok {
		r1 = rf(ctx, cep)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.CustomError)
		}
	}

	return r0, r1
}

// NewMockGetTemperatureByCepUsecase creates a new instance of MockGetTemperatureByCepUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetTemperatureByCepUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetTemperatureByCepUsecase {
	mock := &MockGetTemperatureByCepUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
