// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Berchon/weather-cloud-run/internal/business/model"
)

// MockViaCepService is an autogenerated mock type for the ViaCepService type
type MockViaCepService struct {
	mock.Mock
}

// GetAddressByZipCode provides a mock function with given fields: ctx, zipCode
func (_m *MockViaCepService) GetAddressByZipCode(ctx context.Context, zipCode model.ZipCode) (*string, *model.CustomError) {
	ret := _m.Called(ctx, zipCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressByZipCode")
	}

	var r0 *string
	var r1 *model.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, model.ZipCode) (*string, *model.CustomError)); ok {
		return rf(ctx, zipCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ZipCode) *string); ok {
		r0 = rf(ctx, zipCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ZipCode) *model.CustomError); ok {
		r1 = rf(ctx, zipCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.CustomError)
		}
	}

	return r0, r1
}

// NewMockViaCepService creates a new instance of MockViaCepService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViaCepService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViaCepService {
	mock := &MockViaCepService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
